/**
 * Douyin login + cookies.txt export.
 *
 * One-time / occasional command. Launches NON-HEADLESS Chrome with the
 * persistent Douyin profile, navigates to douyin.com, waits ${WAIT_SECONDS}
 * for the user to login (or just to let cookies hydrate), then dumps all
 * douyin.com cookies via CDP Network.getAllCookies to cookies.txt in
 * Netscape format that yt-dlp accepts via --cookies.
 *
 * Why this exists: yt-dlp's --cookies-from-browser chrome fails on Windows
 * when Chrome is running (DPAPI decrypt error). By extracting cookies via
 * the CDP session we control, we bypass that limitation entirely.
 *
 * Usage:
 *   node src/douyin/login-export.mjs                       # default 60s wait, opens window
 *   node src/douyin/login-export.mjs --wait 120            # 2 min wait
 *   node src/douyin/login-export.mjs --headless --wait 15  # quick headless refresh
 *   node src/douyin/login-export.mjs --url <video_url>     # warm cookies for this specific video page
 *
 * Side effects:
 *   - D:/tiktok/douyin/cookies.txt   (Netscape format for yt-dlp --cookies)
 *   - D:/tiktok/douyin/ua.txt        (Chrome User-Agent string, used by yt-dlp --user-agent)
 */
import "../env.js";
import { spawn, spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { DOUYIN_CONFIG } from "./config.mjs";
import { createLogger } from "./utils/log.mjs";

const log = createLogger(DOUYIN_CONFIG.logFile);
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

const args = process.argv.slice(2);
const HEADLESS = args.includes("--headless");
const WAIT_SECONDS = args.includes("--wait")
  ? parseInt(args[args.indexOf("--wait") + 1]) || 60
  : (HEADLESS ? 8 : 60);
const URL_OVERRIDE = args.includes("--url")
  ? args[args.indexOf("--url") + 1]
  : null;

function pickPort() {
  return DOUYIN_CONFIG.chromeRemotePortBase + 50 + Math.floor(Math.random() * 50);
}

/** Convert CDP cookies → Netscape cookies.txt format. */
function toNetscape(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by douyin/login-export.mjs", ""];
  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
    const includeSubdomains = "TRUE";
    const path = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    // CDP returns expires as seconds (float, -1 for session). Netscape wants integer seconds.
    const expires = c.expires && c.expires > 0
      ? Math.floor(c.expires)
      : Math.floor(Date.now() / 1000) + 365 * 24 * 3600; // 1 year fallback for session cookies
    const name = c.name;
    const value = c.value;
    lines.push([domain, includeSubdomains, path, secure, expires, name, value].join("\t"));
  }
  return lines.join("\n") + "\n";
}

function killStaleChromeForProfile() {
  // Kill any chrome.exe still holding the douyin-cdp-profile (from previous
  // runs that may have left zombies). Critical on Windows: if a stale Chrome
  // is using the profile, a new Chrome.exe launched with same --user-data-dir
  // silently attaches and exits without opening a window.
  try {
    const r = spawnSync("powershell", [
      "-NoProfile", "-Command",
      `Get-CimInstance Win32_Process -Filter "name='chrome.exe'" | ` +
      `Where-Object { $_.CommandLine -like '*douyin-cdp-profile*' } | ` +
      `ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }`
    ], { encoding: "utf8", timeout: 10000 });
    if (r.status === 0) log.info("login-export", "killed stale chrome processes (if any)");
  } catch {}

  // Sleep so OS releases file handles
  spawnSync("powershell", ["-NoProfile", "-Command", "Start-Sleep -Seconds 2"], { timeout: 5000 });

  // Remove lockfiles
  const lockNames = ["lockfile", "SingletonLock", "SingletonCookie", "SingletonSocket"];
  for (const name of lockNames) {
    const p = join(DOUYIN_CONFIG.chromeUserDataDir, name);
    try { if (existsSync(p)) unlinkSync(p); } catch {}
  }
}

async function main() {
  const port = pickPort();
  mkdirSync(DOUYIN_CONFIG.chromeUserDataDir, { recursive: true });
  mkdirSync(DOUYIN_CONFIG.baseDir, { recursive: true });
  const cookiesPath = join(DOUYIN_CONFIG.baseDir, "cookies.txt");

  // Pre-flight: clear stale Chrome + lockfiles for this profile
  killStaleChromeForProfile();

  const initialUrl = URL_OVERRIDE || "https://www.douyin.com";

  const chromeArgs = [
    HEADLESS ? "--headless=new" : "--start-maximized",
    "--disable-gpu",
    `--remote-debugging-port=${port}`,
    `--user-data-dir=${DOUYIN_CONFIG.chromeUserDataDir}`,
    "--no-first-run",
    "--disable-blink-features=AutomationControlled",
    initialUrl,
  ];

  log.info("login-export", `launching Chrome (${HEADLESS ? "headless" : "windowed"}) on port ${port}`);
  if (!HEADLESS) {
    console.log(`\n========================================`);
    console.log(`  Chrome đang mở — vui lòng login Douyin`);
    console.log(`  Tự động dump cookies sau ${WAIT_SECONDS}s`);
    console.log(`========================================\n`);
  }

  const proc = spawn(`"${DOUYIN_CONFIG.chromePath}"`, chromeArgs, {
    shell: true, detached: true, stdio: "ignore",
  });
  proc.unref();

  // Retry CDP connection — headless Chrome can be slow to bind debug port
  let tabs = null;
  for (let attempt = 1; attempt <= 12; attempt++) {
    await sleep(2000);
    try {
      const tabsRes = await fetch(`http://localhost:${port}/json`, { signal: AbortSignal.timeout(3000) });
      tabs = await tabsRes.json();
      if (Array.isArray(tabs) && tabs.length > 0) break;
    } catch (e) {
      if (attempt === 12) throw new Error(`CDP not reachable on port ${port} after 24s: ${e.message}`);
    }
  }

  try {
    const tab = tabs.find(t => t.type === "page") || tabs[0];
    if (!tab?.webSocketDebuggerUrl) throw new Error("No CDP tab found");

    const { default: WS } = await import("ws");
    const ws = new WS(tab.webSocketDebuggerUrl);
    await new Promise((res, rej) => { ws.on("open", res); ws.on("error", rej); });

    const cdp = (method, params = {}) => new Promise((res, rej) => {
      const id = Math.floor(Math.random() * 1e8);
      const handler = d => {
        const m = JSON.parse(d.toString());
        if (m.id === id) { ws.off("message", handler); res(m.result); }
      };
      ws.on("message", handler);
      ws.send(JSON.stringify({ id, method, params }));
      setTimeout(() => { ws.off("message", handler); rej(new Error(`CDP timeout: ${method}`)); }, 20000);
    });

    await cdp("Page.enable");
    await cdp("Network.enable");

    log.info("login-export", `waiting ${WAIT_SECONDS}s for cookies to hydrate / user to login`);
    await sleep(WAIT_SECONDS * 1000);

    // Capture user-agent — needed by yt-dlp to match the session
    const uaRes = await cdp("Runtime.evaluate", {
      expression: "navigator.userAgent",
      returnByValue: true,
    });
    const userAgent = uaRes?.result?.value || "";

    const { cookies } = await cdp("Network.getAllCookies");
    const douyinCookies = cookies.filter(c =>
      c.domain.includes("douyin.com") || c.domain.includes("snssdk.com") || c.domain.includes("bytedance"));
    log.info("login-export", `dumped ${douyinCookies.length} cookies (filtered from ${cookies.length} total)`);

    writeFileSync(cookiesPath, toNetscape(douyinCookies));
    writeFileSync(join(DOUYIN_CONFIG.baseDir, "ua.txt"), userAgent);
    log.info("login-export", `✅ wrote ${cookiesPath}`);
    log.info("login-export", `✅ wrote ua.txt: ${userAgent.slice(0, 80)}...`);
    console.log(`\n✅ Cookies saved to: ${cookiesPath}`);
    console.log(`✅ User-Agent saved to: ${join(DOUYIN_CONFIG.baseDir, "ua.txt")}`);
    console.log(`   yt-dlp will use these automatically via download.mjs.\n`);

    ws.close();
  } finally {
    try { proc.kill(); } catch {}
    spawnSync(`taskkill /F /PID ${proc.pid} 2>nul`, { shell: true, timeout: 5000 });
  }
}

main().catch(e => { console.error(e); process.exit(1); });
